### PR TITLE
Live Downloads Page

### PR DESCRIPTION
**Pull request by LutraVibes**
Added a downloads page with respective CSS styling, and added separator to menu drop-down.

Downloads Page uses GitHub's API to download from the latest release.

Android releases cannot be downloaded, as the officially supported method is through Obtainium, so user is either redirected towards the Android installation section of the README, or is forced to refresh the page.

Windows release MSGC and MSYS2 are in a drop-down.

### CODE REVIEW

**Review by LimeGradient — CHANGES_REQUESTED** [review]
Remove the About, FAQ, and TODO from the dropdown in index.html and downloading the APK is still a supported way of using Lime3DS, so the confirm message isnt needed.

**Comment by LutraVibes** [comment]
OpenSauce said that Obtainium was the way to install it

**Comment by LutraVibes** [comment]
He was very vague about it

**Comment by LutraVibes** [comment]
Done

**Review by Polarzincomfrio — CHANGES_REQUESTED** [review]
Windows dropdown should be fixed (it pushing the MacOS one down looks bad) and the android one should have instructions for Obtanium while also having the download link for the apk

**Comment by LutraVibes** [comment]
AAA

**Comment by LutraVibes** [comment]
Don't open it
I'm redoing it all

**Pull request closed without merging**
